### ISSUE TITLE
Feature Request: OnRetrySuccess

### ISSUE THREAD

**Issue by TheColonel2688** [z4kn4fein/trybot#2]
Could we have an OnRetrySuccess() method? That is called after a retry is completed successfully?

I am using TryBot Retry together with Stateless (A StateMachine Library) and I need to beable to signal to the statemachine that a retry succeeded.

Sample usage.

	var policyForCommands = new BotPolicy();

	policyForCommands.Configure(config => config
		.Retry(retryconfig => retryconfig
			.WhenExceptionOccurs(exception => exception is Exception)
			.WithMaxAttemptCount(5)
			.OnRetry((exception, context) =>
			{
				Console.WriteLine("Retrying ");
				//** StateMachine Change State To "ErrorOccured"
			})
			.OnRetrySuccess((Context) => 
			{
				Console.WriteLine("Retry Succeeded");
				//** StateMachine Change State To "Connected"
			})
			)
		.Fallback(fallbackConfig => fallbackConfig
			.WhenExceptionOccurs((exception) => exception is Trybot.Retry.Exceptions.MaxRetryAttemptsReachedException)
			.OnFallback((exception, context) =>
			{
				Console.WriteLine("Retries Failed");
				//** StateMachine Change State To "TryingToReconnect"
			})
			)
	);

**Comment by z4kn4fein** [comment]
And this also!

**Comment by TheColonel2688** [comment]
That's great this would help a lot in cleaning up and a lot of my code and making it more readable.

**Comment by z4kn4fein** [comment]
Hey, this one is available on my [pre-release feed](https://www.myget.org/feed/pcsajtai/package/nuget/trybot), could you please try it that it works as it's expected for you?

**Comment by TheColonel2688** [comment]
yes, I won't get to it tonight but, i should have some time to try it tomorrow night.

thank you this will make my current project much cleaner.

**Comment by TheColonel2688** [comment]
@z4kn4fein I ran it tonight. it seems that OnRetrySuccess will be called even if the first attempt succeeds. I would expect it to only be called if an attempt failed, at least once. Just like OnRetry is only called after the first attempt fails and not before.

**Comment by z4kn4fein** [comment]
Yep, you are right, i'll fix that!

**Comment by z4kn4fein** [comment]
Pushed a new version, could you please try it again?

**Comment by TheColonel2688** [comment]
Yeah, I'll try to get to it today, If not today it will probably be tomorrow night.

**Comment by TheColonel2688** [comment]
Seems to be working the way correctly now.

Thank you very much appreciate the quick feature implementation

**Comment by z4kn4fein** [comment]
released in [2.4.3](https://github.com/z4kn4fein/trybot/releases/tag/2.4.3)
